
///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2021 Cadence Design Systems, Inc. All rights reserved worldwide.
//
// The code contained herein is the proprietary and confidential information 
// of Cadence or its licensors, and is supplied subject to a previously 
// executed license and maintenance agreement between Cadence and customer. 
// Permission is only granted for use with Cadence high-level synthesis tools and
// may not be used with other high-level synthesis tools. Permission is only 
// granted to distribute the code as indicated. Cadence grants permission for 
// customer to distribute a copy of this code to any partner to aid in designing 
// or verifying the customer's intellectual property, as long as such 
// distribution includes a restriction of no additional distributions from the 
// partner, unless the partner receives permission directly from Cadence.
//
// ALL CODE FURNISHED BY CADENCE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
// KIND, AND CADENCE SPECIFICALLY DISCLAIMS ANY WARRANTY OF NONINFRINGEMENT, 
// FITNESS FOR A PARTICULAR PURPOSE OR MERCHANTABILITY. CADENCE SHALL NOT BE 
// LIABLE FOR ANY COSTS OF PROCUREMENT OF SUBSTITUTES, LOSS OF PROFITS, 
// INTERRUPTION OF BUSINESS, OR FOR ANY OTHER SPECIAL, CONSEQUENTIAL OR 
// INCIDENTAL DAMAGES, HOWEVER CAUSED, WHETHER FOR BREACH OF WARRANTY, 
// CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE.
//
////////////////////////////////////////////////////////////////////////////////


// Generated by bdw_memgen 23.02-s004
// Tue Apr 28 11:06:09 CST 2026



#ifndef RAM_8X8_1RW_H
#define RAM_8X8_1RW_H

#include "systemc.h"
#include "stratus_hls.h"


#if !defined(STRATUS_VLG)
#include "cynw_comm_util.h"
#include "cynw_fifo.h"
#endif
#include "cynw_memory.h"
#if defined STRATUS  &&  ! defined CYN_DONT_SUPPRESS_MSGS
#pragma cyn_suppress_msgs NOTE
#pragma hls_ip_def NOTE
#endif	// STRATUS  &&  CYN_DONT_SUPPRESS_MSGS
#if !defined(STRATUS_VLG)
#endif


#if defined(STRATUS_VLG) || defined(STRATUS_HLS)
SC_MODULE(RAM_8X8_1RW)
#else
struct RAM_8X8_1RW
  : public sc_module,
    public cynw_memory_if< sc_uint<3>, sc_uint<8> >
#endif
    {
	HLS_EXTERNAL_MODULE;

   sc_in< bool > CLK;
   sc_in< bool > WE0;
   sc_in< sc_uint<8> > DIN0;
   sc_out< sc_uint<8> > DOUT0;
   sc_in< sc_uint<3> > A0;
   sc_uint<8> mem[8];
 
 

#if defined(__GNUC__) 
    cynw_memory_if< sc_uint<3>, sc_uint<8> >* m_iface;

    void set_iface( cynw_memory_if< sc_uint<3>, sc_uint<8> >* iface ) {
        m_iface = iface;
    }
    void sync_get( uint64 a ) {
       if ( m_iface ) {
           mem[ a ] = m_iface->get( a );
       }
    }
    void sync_put( uint64 a ) {
       if ( m_iface ) {
           m_iface->put( a, mem[ a ] );
       }
    }
#endif
#ifdef STRATUS_HLS
   sc_uint<8> read0(sc_uint<3> A0, bool WE0=1);

#endif	// STRATUS_HLS
#ifdef STRATUS_HLS
   sc_uint<8> write0(sc_uint<3> A0, sc_uint<8> DIN0, bool WE0=0);

#endif	// STRATUS_HLS
#ifdef STRATUS_HLS
   void nop0(bool WE0=1);

#endif	// STRATUS_HLS
 
   void thread0();

 
#if defined(STRATUS_VLG)
   SC_CTOR( RAM_8X8_1RW );

#else
   SC_HAS_PROCESS( RAM_8X8_1RW );

   RAM_8X8_1RW( sc_module_name name = sc_module_name(sc_gen_unique_name("RAM_8X8_1RW")));
#endif
   static const unsigned long implemented;
   static const unsigned long pipelined;
   static const float area;
   static const float delay;
   static const float setup_time;
   static const unsigned long latency_WE0;
   static const unsigned long latency_DIN0;
   static const unsigned long latency_A0;
   static const unsigned long reg_mem_inputs;
   static const unsigned long reg_mem_outputs;
   static const unsigned long regs_at_mem_inputs;
   static const unsigned long regs_at_mem_outputs;
   static const unsigned long no_spec_reads;
   static const unsigned long is_mem;
   static const unsigned long clock_multiplier;
   static const bool has_extra_ports;
   static const bool is_prototype;
   static const char* naming_convention;


   typedef sc_uint<3>                       address_type;
   typedef sc_uint<8>                      data_type;
   
    enum {
        pipeline_depth = 1,
        mem_size = 8,
        SIZE = 8,
        address_width = 3,
        data_width = 8
    };


#if !defined(STRATUS_VLG) && !defined(STRATUS_HLS)
   // 
   // cynw_memory_if
   //
   data_type get( const address_type& address )
   {

#if defined(__GNUC__) && defined(BDW_TRACE_MEMS)
        fprintf(stderr,"TRACE: %s: %s: read 0x%s from 0x%x\n", name(), sc_time_stamp().to_string().c_str(), mem[address.to_uint()].to_string(SC_HEX).c_str(), (int)address.to_uint());
#endif
        return mem[address.to_uint()];
   }
   void put( const address_type& address, const data_type& data )
   {

#if defined(__GNUC__) && defined(BDW_TRACE_MEMS)
        fprintf(stderr,"TRACE: %s%s: %s: write 0x%s to 0x%x\n", name(), "", sc_time_stamp().to_string().c_str(), data.to_string(SC_HEX).c_str(), (int)address.to_uint());
#endif
        mem[address.to_uint()] = data;
#if defined(__GNUC__)
            sync_put(address.to_uint());
#endif

}

#endif

#if defined(__GNUC__) && BDW_USE_SCV
    cynw_scv_memory_tx_stream< sc_uint<3>, sc_uint<8> >* m_p1_tx_stream;
    cynw_scv_memory_tx< sc_uint<3>, sc_uint<8> > m_p1_tx_0;
#endif
    template <typename HLS_L=CYN::PIN> struct types;
};

// 
// struct containing signals to which a metaport can be bound
// 
struct RAM_8X8_1RW_ext_signals_1
{
    RAM_8X8_1RW_ext_signals_1( const char* prefix=0 ) 
        :WE0(sc_gen_unique_name(HLS_CAT_NAMES(prefix,"WE0")))
        ,REQ0(sc_gen_unique_name(HLS_CAT_NAMES(prefix,"REQ0")))
        ,DIN0(sc_gen_unique_name(HLS_CAT_NAMES(prefix,"DIN0")))
        ,DOUT0(sc_gen_unique_name(HLS_CAT_NAMES(prefix,"DOUT0")))
        ,A0(sc_gen_unique_name(HLS_CAT_NAMES(prefix,"A0")))
    {}
   HLS_SC_SIGNAL_DECL( bool, true ) WE0;
   HLS_SC_SIGNAL_DECL( bool, true ) REQ0;
   HLS_SC_SIGNAL_DECL( sc_uint<8>, true ) DIN0;
   HLS_SC_SIGNAL_DECL( sc_uint<8>, true ) DOUT0;
   HLS_SC_SIGNAL_DECL( sc_uint<3>, true ) A0;

};

//
// Type declarations
//
// The members of this struct can be accessed directly to 
// identify a type related to this memory model.
//
template <typename HLS_L>
struct RAM_8X8_1RW::types
{  
    typedef sc_uint<3>                       address_type;
    typedef sc_uint<8>                      data_type;
    typedef sc_int<8>                       signed_type;
    typedef RAM_8X8_1RW                             mem_type;
    typedef RAM_8X8_1RW_ext_signals_1             ext_signals_1;

   
    enum {
        pipeline_depth = 1,
        mem_size = 8,
        SIZE = 8,
        address_width = 3,
        data_width = 8
    };

};

#endif // RAM_8X8_1RW_H

