import cv2
import numpy as np


# Doing Approximate_median_3x3
def approximate_median_3x3(img):
    padded = np.pad(img, 1, mode="constant", constant_values=0)
    h, w = img.shape
    out = np.zeros_like(img)
    for y in range(h):
        for x in range(w):
            window = padded[y : y + 3, x : x + 3]

            row0_med = sorted(window[0])[1]
            row1_med = sorted(window[1])[1]
            row2_med = sorted(window[2])[1]

            final_med = sorted([row0_med, row1_med, row2_med])[1]
            out[y, x] = final_med

    return out


# Code generated by ChatGPT


def conv2d(image, kernel, stride=1, padding=0):
    """
    Perform 2D convolution on an input image using the given kernel.

    Parameters:
    - image (numpy.ndarray): Input 2D array (grayscale image)
    - kernel (numpy.ndarray): 2D filter to apply
    - stride (int): Step size for moving the kernel
    - padding (int): Number of pixels to pad around the image

    Returns:
    - numpy.ndarray: The result of the convolution operation
    """

    # Get dimensions
    img_h, img_w = image.shape
    kernel_h, kernel_w = kernel.shape

    # Apply padding
    if padding > 0:
        image = np.pad(
            image,
            ((padding, padding), (padding, padding)),
            mode="constant",
            constant_values=0,
        )

    # Compute output dimensions
    out_h = (image.shape[0] - kernel_h) // stride + 1
    out_w = (image.shape[1] - kernel_w) // stride + 1

    # Initialize output
    output = np.zeros((out_h, out_w))

    # Perform convolution
    for i in range(out_h):
        for j in range(out_w):
            region = image[
                i * stride : i * stride + kernel_h, j * stride : j * stride + kernel_w
            ]
            output[i, j] = np.sum(region * kernel)

    return output


def add_noise(img, n):
    img2 = img
    for _ in range(n):
        x = int(np.random.random() * img.shape[0])
        y = int(np.random.random() * img.shape[1])
        img2[x, y] = 156  # white in gray scale is 255
    return img2


if __name__ == "__main__":
    # Input original image file
    # To use another image input file, please change the filename
    # Also the downloaded 'standard_test_images/' should be in the same folder
    filename = "lena_color_256"
    img = cv2.imread(f"./standard_test_images/{filename}.tif")
    # Write out original image in color bmp format
    # cv2.imwrite(f'./{filename}.bmp', img)
    # Convert to grayscale image
    image_gray = cv2.cvtColor(src=img, code=cv2.COLOR_BGR2GRAY)
    # Write out original image in grayscale bmp format (golden)
    # cv2.imwrite(f"./{filename}_gray.bmp", image_gray)
    # cv2.imwrite(f"./{filename}_gray.bmp", img)

    # Add white noise points and write out another bmp file
    # noise_img = add_noise(image_gray, 100)
    # cv2.imwrite(f"./{filename}_gray_noise.bmp", noise_img)

    # Apply Median Filter and Save Output
    # noise_img_M = cv2.medianBlur(noise_img, 3)
    noise_img_M = approximate_median_3x3(image_gray)
    # cv2.imwrite(f"{filename}_gray_noise_median.bmp", noise_img_M)

    scharr_x = np.array([[-3, 0, 3], [-10, 0, 10], [-3, 0, 3]])

    scharr_y = np.array([[-3, -10, -3], [0, 0, 0], [3, 10, 3]])

    grad_x = conv2d(noise_img_M, scharr_x, stride=1, padding=1)
    grad_y = conv2d(noise_img_M, scharr_y, stride=1, padding=1)

    grad_combined = np.sqrt(np.square(grad_x) + np.square(grad_y))

    final_edge = np.round(grad_combined)
    final_edge = np.clip(final_edge, 0, 255).astype(np.uint8)

    cv2.imwrite(f"gold_{filename}.bmp", final_edge)
    # cv2.imwrite(f"{filename}_scharr_edge.bmp", final_edge)
