FROM ubuntu:22.04
LABEL maintainer = "EE6470"

ENV DEBIAN_FRONTEND noninteractive

# Set apt mirror, using NCHC's server
RUN sed -i 's/archive.ubuntu.com/free.nchc.org.tw/g' \
    /etc/apt/sources.list
# Update
RUN apt-get update
RUN apt-get upgrade -y
# Install missing system-tools
RUN apt-get install software-properties-common locales -y
# Set locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
# Install build tools
RUN apt-get install -y \
    cmake ninja-build \
    build-essential \
    device-tree-compiler
# Install LLVM toolchain
RUN apt-get install -y clang
# Install python3
RUN apt-get install -y \
    python3 python3-dev \
    python3-pip
# Install common tools
RUN apt-get install -y \
    vim git tmux wget curl p7zip \
    clang-format clang-tidy \
    gdb valgrind fish

# Install depedencies
RUN apt-get install -yq autoconf automake perl flex

# Install System C library 
RUN apt-get install -y libsystemc libsystemc-dev libsystemc-doc

# Install Boost library
RUN apt-get install -y libboost-all-dev

# Install Doxygen
RUN apt-get install -y doxygen

# Install packages to build RISC-V toolchain
RUN apt-get install -y autotools-dev libmpc-dev libmpfr-dev libgmp-dev gawk bison texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev libboost-iostreams-dev

# Install xpack RISC-V embedded toolchain 
# For ARM-based (aarch64) system (Mac M1/M2/M3)
RUN wget -q https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v13.2.0-2/xpack-riscv-none-elf-gcc-13.2.0-2-linux-arm64.tar.gz && \
    tar xzvf xpack-riscv-none-elf-gcc-13.2.0-2-linux-arm64.tar.gz && rm  xpack-riscv-none-elf-gcc-13.2.0-2-linux-arm64.tar.gz && \
    mv xpack-riscv-none-elf-gcc-13.2.0-2 /opt/riscv-gnu-toolchain
# Set PATH
RUN sed -e 's|PATH="\(.*\)"|PATH="/opt/riscv-gnu-toolchain/bin:\1"|g' -i /etc/environment

# Cleanup
RUN apt-get autoremove -y \
    && apt-get autoclean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/*

# Use bash as default shell
RUN ln -sf /bin/bash /bin/sh

# Leave this as the default directory (just clean)
WORKDIR /root/

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh

#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]

