#ifndef SYSTEM_H_
#define SYSTEM_H_

#include "Testbench.h"
#include "hls_def.h"
#include <systemc>

#ifndef NATIVE_SYSTEMC
#include "HammingMatch_wrap.h" // generated by Stratus
#else
#include "HammingMatch.h"
#endif

using namespace sc_core;

class System : public sc_module {
public:
  SC_HAS_PROCESS(System);
  System(sc_module_name n, std::string train_file, std::string query_file);
  ~System();

private:
  Testbench tb;

#ifndef NATIVE_SYSTEMC
  HammingMatch_wrapper hm; // Stratus wrapper
#else
  HammingMatch hm;
#endif

  sc_clock clk;
  sc_signal<bool> rst;

  // Descriptor Channels
  HLS_CHAN(sc_dt::sc_uint<32>) train_ch;
  HLS_CHAN(sc_dt::sc_uint<32>) query_ch;
  HLS_CHAN(sc_dt::sc_uint<8>) best_idx_ch;
  HLS_CHAN(sc_dt::sc_uint<9>) min_dist_ch;
};

#endif // !SYSTEM_H_
